### ISSUE TITLE
api/gtaPeriode/POST/{ID_PERIODE}/refuser retourne ne retourne pas de status HTTP en cas d'erreur

### ISSUE THREAD

**Issue by killiankopp** [pebble-solutions/App-GTA-manager#33]
Lorsqu'une GtaPeriode est validée ou refusée avec une erreur, le code HTTP n'est pas correctement retourné (code 20X au lieu de 50X).

**Comment by Guillaume35** [comment]
Résolut dans une mise à jour de l'API
